#!/usr/bin/env ansible-playbook

- name: Group hosts by distribution 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distro
      group_by: key={{ ansible_distribution }}

- name: Install MongoDB
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: Install Repository keys
      apt_key: state=present keyserver=keyserver.ubuntu.com id=7F0CEB10
    - name: Install MongoDB repository
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present
    - name: Install MongoDB
      apt: name=mongodb-org state=latest update_cache=true cache_valid_time=600

